### ISSUE TITLE
aeroo-docs start: error: too few arguments

### ISSUE THREAD

**Issue by lethanhthien** [aeroo/aeroo_docs#11]
Hi,
I follow link(https://www.odoo.com/nl_NL/forum/help-1/question/8-0-how-can-i-install-the-official-aeroo-reports-alistek-for-odoo-version-8-solved-installation-script-76044) instructions. But when I start service aeroo-docs, I get the error:
usage: aeroo-docs start [-h] [-c CONFIG_FILE] [-i INTERFACE] [-p PORT]
                        [-w OO_SERVER] [-s OO_PORT] [-d SPOOL_DIRECTORY]
                        [-e SPOOL_EXPIRE] [-t] [-n] [-l LOG_FILE]
                        [-f PID_FILE]
                        {--simple-auth} ...
aeroo-docs start: error: too few arguments
ps: I using Ubuntu 12.04 OS

I have done something wrong ?

Thanks for your help.

**Comment by scigghia** [comment]
i get the same error
Debian Wheezy

**Comment by sysadminmatmoz** [comment]
same issue, default config is not createds

**Comment by scigghia** [comment]
error is here: https://github.com/aeroo/aeroo_docs/blob/master/aeroo-docs#L315
also with no config, because script create its internal conf

**Comment by scigghia** [comment]
no one has this same problem?

**Comment by StefanRijnhart** [comment]
You are not alone.

**Comment by StefanRijnhart** [comment]
This comment confirms a problem with Wheezy's Python 3.2 and the optional subparser arguments: https://bugs.python.org/issue9253#msg186387. This affects both the simple-auth bit and the action (start/stop/restart). There is another minor issue with mkdir not taking the positional *mode* argument in this version of Python.

I can get the script to run by ripping out the simple auth options, changing the mode argument of mkdir into a positional argument and taking out the *stop* and *restart* commands as well. And even then, the script seems to ignore all the parameters in the config file. I'm now simply hardcoding my values in the script, and need to write an init script that simply kills the daemon.

**Comment by scigghia** [comment]
hi any news ?
@StefanRijnhart would you share your script?

**Comment by StefanRijnhart** [comment]
Sorry, I upgraded to Debian Jessie. Problem solved.

**Comment by scigghia** [comment]
ok, i'll try
tnx

**Comment by scigghia** [comment]
it works on jessie

thanks
