### ISSUE TITLE
Install aeroo_docs on ubuntu 15.04

### ISSUE THREAD

**Issue by rjpathan** [aeroo/aeroo_docs#14]
I tried to install aeroo_docs on Ubuntu 15.04 by following same instructions for installing aeroo_docs on ubuntu 14.04.

I think installation was done but got following output on starting service:

odoo@erp:/opt/aeroo$ sudo service aeroo-docs start
Failed to start aeroo-docs.service: Unit aeroo-docs.service failed to load: No such file or directory.

**Comment by osluys** [comment]
I get the same error on Ubuntu Server 15.10 when using the service command, but running the script directly works without problems.

**Comment by AyaYousef** [comment]
Same problem here on UBUNTU 15.04

**Comment by rjpathan** [comment]
Follow attached guide to install Aeroo reporting.

[install_aeroo.pdf](https://github.com/aeroo/aeroo_docs/files/250079/install_aeroo.pdf)
