### ISSUE TITLE
How to install/use?

### ISSUE THREAD

**Issue by Sathors** [aeroo/aeroo_docs#3]
Hi,

I was using lately the report_aeroo from jamotion, and now that you have released this version compatible with Odoo8, I would like to use it instead.

The thing is that I couldn't find any installation instructions, and for a change I am struggling with the dependencies.
As a side note I think it would be nice to have at least a dependencies list to know what python packages are needed.
Am I supposed to install other aeroo python libraries? I tried cloning the aeroo/aeroolib package, and installing it issuing a `sudo python3 setup.py install`, and it gives me the error
`
File "setup.py", line 15
    maintainer=u"Alistek Ltd",
                            ^
SyntaxError: invalid syntax
`

So I am on Ubuntu 12.04, I was trying to use aeroo_docs, installed the different python3 packages that were giving me errors, and now I am stuck on the version of python-uno.

I am installing the python3 version of the uno package using pip , and when issuing a `./aeroo-docs -h`, I get the error
`
Traceback (most recent call last):
  File "./aeroo-docs", line 42, in <module>
    from aeroo_docs_fncs import OfficeService
  File "/home/nicolas/odoo/olympo_extras8/addons/aeroo_docs/aeroo_docs_fncs.py", line 30, in <module>
    from DocumentConverter import DocumentConverter, DocumentConversionException
  File "/home/nicolas/odoo/olympo_extras8/addons/aeroo_docs/DocumentConverter.py", line 38, in <module>
    import uno
  File "/usr/local/lib/python3.2/dist-packages/uno/__init__.py", line 4, in <module>
    from base import Element, Css, Payload, UnoBaseFeature, UnoBaseField
ImportError: No module named base
`

Thanks for your help.

**Comment by sraps** [comment]
There are two problems:
1. lack of up to date install manual for Aeroo Reports and Aeroo DOCS;
For short, you should install Aeroo Reports library (aeroolib) using python 2.x, while Aeroo DOCS using python 3.x. This is due to need for decoupling Odoo process from LibrOffice and it's libraries which is running on Python 3.

2. "Traceback (most recent call last)..." 
This is due to latest updates of LibreOffice (at least I guess so). At least I recently stumbled upon similar error. Did many things, like complete LibreOffice reinstall, still I think you need to restart the OS first, then might need to reinstall the LO as I did. It's something related to location of UNO python library in addons directory structure, still not sure.

**Comment by Sathors** [comment]
To begin with @sraps , thanks for the quick answer, it seems you are quite active.

Regarding point 1, I think that you would really ease the installation process for your users if you were giving these recommendations on the repo README.
As well, is the command to run the soffice service the same one than before? Well I guess more instructions are given with the `aeroo-docs --help`, that's way I didn't ask it before.

As for point 2, if it may help you I have LO 4.4.0.3, which is not the standard one in the precise repos.

Thanks for your help.

**Comment by sraps** [comment]
About the 2nd point, I can only say that I have several Mint  installations with Aeroo DOCS installed, for which I do updates at a various frequency. On several of them (which I do reboot frequently) I did not experience the problem at all, the others I did not reboot frequently I experienced the problem. But reboot seemingly fixed it, so I guess it's the resolution.

**Comment by colml** [comment]
I added a page to the wiki showing an install example: https://github.com/aeroo/aeroo_docs/wiki/Installation-example-for-Ubuntu-14.04-LTS

This is only for the aeroo-docs service. A complete example can probably be added to the aeroo_reports wiki later.

**Comment by Sathors** [comment]
@sraps , I tried rebooting as you advised me, but it didn't change anything at all.

@colml, thanks for the install example. Following your instructions on a fresh Ubuntu 14.04 install, it does indeed work. I think it would be nice also to provide an Ubuntu 12.04 installation instructions, because many people (companies) still use it.

The thing is that one needs the official python3-uno package, which does not seem the same that the uno package installed using pip3.

When I try to install python3-uno package, Ubuntu complains with:
`
The following packages have unmet dependencies:
 python3-uno : Depends: libreoffice-core (= 1:3.5.7-0ubuntu7) but 1:4.4.0~rc3-0ubuntu1~precise1 is to be installed
E: Unable to correct problems, you have held broken packages.
`
So it seems that to install aeroo-docs, I would need to downgrade my LibreOffice installation.

Thanks for the help though, I mark it as closed.

**Comment by colml** [comment]
@Sathors, the python3-uno package needs to match the version of LibreOffice you installed. Version 3.5.7 is the current default for Ubuntu 12.04. Did you install LibreOffice from another source? If so, use the python3-uno package from there.

**Comment by sraps** [comment]
Probably it would make sense to assemble table with python3-uno versions compatible with certain versions of LibreOffice / OpenOffice.

**Comment by Sathors** [comment]
@sraps , I think it is a good idea indeed. The strange thing is that it seems natural to me that the version in the Python Package Index would be newer than the one in the Ubuntu 12.04, thus compatible with the latest version of LibreOffice.

I will look around to see if I can find another working version.
