### ISSUE TITLE
Error: name '_readFile' is not defined

### ISSUE THREAD

**Issue by mstuttgart** [aeroo/aeroo_docs#7]
When I run AerooDocs in Odoo v8 in menu *configuration->Configure Docs Connection*, it return the following error:

**"name '_readFile' is not defined"**

This error is on line 107 of [aeroo_docs_fncs.py](https://github.com/aeroo/aeroo_docs/blob/master/aeroo_docs_fncs.py) file:

``
data = _readFile(identifier)
``
https://github.com/aeroo/aeroo_docs/blob/master/aeroo_docs_fncs.py#L107

I fixed it changed the code to:
```
data = self._readFile(identifier)
```

**Comment by mstuttgart** [comment]
I will make a fork and submit the changes.

**Comment by JayVora-SerpentCS** [comment]
Nice catch!

**Comment by alexis-via** [comment]
This bug is now fixed in master.

**Comment by mstuttgart** [comment]
Thanks!
